[workspace]
resolver = "3"
members = [
	"packages/cli", "packages/nvim-config",
]

[workspace.package]
authors = ["Daiki48"]
description = "My dotfiles"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.98"
