return {
  require("plugins.snacks"),
  require("plugins.sakurajima"),
  require("plugins.editorconfig-vim"),
  require("plugins.lualine"),
  require("plugins.gitsigns"),
  require("plugins.oil"),
  require("plugins.oil-vcs-status"),
  require("plugins.nvim-autopairs"),
  require("plugins.vim-startuptime"),
  -- require("plugins.telescope"),
  -- require("plugins.coc"),
  require("plugins.vim-svelte-plugin"),
  require("plugins.treesitter"),
  require("plugins.nvim-ts-autotag"),
  require("plugins.codesnap"),
  require("plugins.flash"),
  require("plugins.which-key"),
  require("plugins.blink-cmp"),
  require("plugins.nvim-lspconfig"),
}
